language: python
python: 3.6
sudo: required

services:
  - docker

before_install:
  - docker pull quay.io/teknoradio.org/base
  - docker ps -a

install:
  - pip install -q testinfra --use-wheel

script:
  - docker build --cache-from quay.io/teknoradio.org/base -t teknoradio/base .
  - docker run --rm --name base teknoradio/base /bin/bash -c "which curl" | grep -q /usr/bin/curl
  - py.test --connection=docker -v

notifications:
  email : false
