sudo: required

language: bash

services:
  - docker

before_install:
  - docker pull ubuntu:16.04

install:
  - docker build -t teknoradio/base .
  - docker run --name base teknoradio/base

script:
  - docker ps | grep -q base

