sudo: required

language: bash

services:
  - docker

before_install:
  - docker pull ubuntu:16.04


script:
  - docker build -t teknoradio/base .
  - docker run --rm --name base teknoradio/base /bin/bash -c "which curl" | grep -q /usr/bin/curl
